name: CI Tests

on:
  pull_request:
    branches:
      - main # Or your main development branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest # Install pytest
          pip install -r requirements.txt # Install other project dependencies if you have a requirements.txt

      - name: Run Pytest tests
        run: |
          pytest